services:

  orng-frontend:
    image: bitmaximum/orng-front:latest
    container_name: ${FRONTEND_HOSTNAME:-orng-frontend}
    hostname: ${FRONTEND_HOSTNAME:-orng-frontend}
    restart: unless-stopped
    ports:
      - "3000:80"
    environment:
      BASE_URL: ${BASE_URL:-https://api.kiberorange.ru}
