version: '3.9'

services:

  orng-auth:
    image: bitmaximum/orng-auth:latest
    container_name: orng-auth
    restart: always
    ports:
      - "8080:8080"
    environment:
      DB_URL: jdbc:postgresql://database:5432/orng?currentSchema=orng_auth
      DB_USER: orng
      DB_PASS: orng
    depends_on:
      - database

  employee-service:
    image: bitmaximum/orng-employee:latest
    ports:
      - "${EM_PORT:-8082}:8080"
    environment:
      DB_URL: jdbc:postgresql://database:${PG_PORT:-5432}/${DB_NAME:-orng}?currentSchema=orng_employee
      DB_USER: ${DB_USER:-orng}
      DB_PASS: ${DB_PASS:-orng}
    depends_on:
      - database
    restart: unless-stopped

  database:
    image: 'postgres:18-alpine'
    container_name: 'postgres-db'
    restart: always
    environment:
      - POSTGRES_USER=orng
      - POSTGRES_PASSWORD=orng
      - POSTGRES_DB=orng
    volumes:
      - db:/var/lib/postgresql/data postgres
    ports:
      - "5432:5432"

volumes:
  db:


#services:
#  postgres:
#    image: postgres:18-alpine
#    container_name: postgres
#    environment:
#      POSTGRES_DB: ${DB_NAME:-orng}
#      POSTGRES_USER: ${DB_USER:-orng}
#      POSTGRES_PASSWORD: ${DB_PASS:-orng}
#    ports:
#      - "${PG_PORT:-5432}:5432"
#    volumes:
#      - pg_data:/var/lib/postgresql/data
#    restart: unless-stopped
#    env_file:
#      - .env
#
#  employee-service:
#    image: rumarsky/orng-employee-service:latest
#    container_name: employee-service
#    ports:
#      - "${EM_PORT:-8082}:8080"
#    environment:
#      DB_URL: jdbc:postgresql://postgres:${PG_PORT:-5432}/${DB_NAME:-orng}?currentSchema=orng_employee
#      DB_USER: ${DB_USER:-orng}
#      DB_PASS: ${DB_PASS:-orng}
#      SERVER_PORT: 8082
#      JWT_PUBLIC_KEY: ${JWT_PUBLIC_KEY:-MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAqlQUwILcSHrTENYjucRMTqq2LdIBkeY518lnZIU9A072houtkrfPUSiGvxYvf/K3TlR9pnhQAq9TU6BU8fPBmzZTqFHmPqoX+btAAFZlI+UOdYe/3T19jldFwk3nQ6JzHZwfHLpOZZZhhCt4Pe+>}
#    depends_on:
#      - postgres
#    restart: unless-stopped
#    env_file:
#      - .env

#  schedule-service:
#    image: rumarsky/orng-schedule-service:latest
#    container_name: schedule-service
#    ports:
#      - "${SS_PORT:-8083}:8080"
#    environment:
#      DB_URL: jdbc:postgresql://postgres:${PG_PORT:-5432}/${DB_NAME}?currentSchema=orng_schedule
#      DB_USER: ${DB_USER:-orng}
#      DB_PASS: ${DB_PASS:-orng}
#      SERVER_PORT: ${SS_PORT:-8083}
#      EMPLOYEE_SERVICE_URL: ${EMPLOYEE_SERVICE_URL:-employee-service:8082}
#      JWT_PUBLIC_KEY: ${JWT_PUBLIC_KEY:-MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAqlQUwILcSHrTENYjucRMTqq2LdIBkeY518lnZIU9A072houtkrfPUSiGvxYvf/K3TlR9pnhQAq9TU6BU8fPBmzZTqFHmPqoX+btAAFZlI+UOdYe/3T19jldFwk3nQ6JzHZwfHLpOZZZhhCt4Pe+>}
#    depends_on:
#      - postgres
#      - employee-service
#    restart: unless-stopped
#    env_file:
#      - .env
#
#volumes:
#  pg_data:

