services:

  orng-auth:
    image: bitmaximum/orng-auth:latest
    container_name: orng-auth
    restart: unless-stopped
    ports:
      - "${AUTH_PORT:-8080}:8080"
    environment:
      DB_URL: jdbc:postgresql://database:${PG_PORT:-5432}/${DB_NAME:-orng}?currentSchema=orng_auth
      DB_USER: orng
      DB_PASS: orng
      ACCESS_TOKEN_EXIRATION_SECONDS: 15
      REFRESH_TOKEN_EXIRATION_SECONDS: 604800
      JWT-ISSUER: orng-auth
      JWT-DEFAULT-USER-SCOPES: ROLE_MANAGER
      LOGGING_LEVEL_DEFAULT: TRACE
      CORS_ALLOWED_ORIGINS: https://kiberorange.ru,http://kiberorange.ru,https://front.kiberorange.ru,http://www.kiberorange.ru,http://localhost:9006,http://127.0.0.1:9006
    depends_on:
      - database

  orng-office:
    image: bitmaximum/orng-office:latest
    container_name: orng-office
    restart: unless-stopped
    ports:
      - "${OFFICE_PORT:-8081}:8080"
    environment:
      DB_URL: jdbc:postgresql://database:${PG_PORT:-5432}/${DB_NAME:-orng}?currentSchema=orng_office
      DB_USER: ${DB_USER:-orng}
      DB_PASS: ${DB_PASS:-orng}
      JWT-ISSUER: orng-auth
      LOGGING_LEVEL_DEFAULT: TRACE
    depends_on:
      - database

  employee-service:
    image: rumarsky/orng-employee:latest
    container_name: employee-service
    ports:
      - "${EM_PORT:-8082}:8080"
    environment:
      DB_URL: jdbc:postgresql://database:${PG_PORT:-5432}/${DB_NAME:-orng}?currentSchema=orng_employee
      DB_USER: ${DB_USER:-orng}
      DB_PASS: ${DB_PASS:-orng}
      OFFICE_SERVICE_URL: orng-office:8080
      LOGGING_LEVEL_DEFAULT: TRACE
    depends_on:
      - database
    restart: unless-stopped

  schedule-service:
    image: rumarsky/orng-schedule:latest
    container_name: schedule-service
    ports:
      - "${SS_PORT:-8083}:8080"
    environment:
      DB_URL: jdbc:postgresql://database:${PG_PORT:-5432}/${DB_NAME:-orng}?currentSchema=orng_schedule
      DB_USER: ${DB_USER:-orng}
      DB_PASS: ${DB_PASS:-orng}
      SERVER_PORT: 8080
      EMPLOYEE_SERVICE_URL: employee-service:8080
      OFFICE_SERVICE_URL: orng-office:8080
      LOGGING_LEVEL_DEFAULT: TRACE
    depends_on:
      - database
      - employee-service
    restart: unless-stopped

  database:
    image: 'postgres:18-alpine'
    container_name: 'postgres-db'
    restart: always
    environment:
      - POSTGRES_USER=orng
      - POSTGRES_PASSWORD=orng
      - POSTGRES_DB=orng
    volumes:
      - db:/var/lib/postgresql/data postgres
      - type: bind
        source: ./init.sql
        target: /docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432:5432"

volumes:
  npm_data:
  npm_letsencrypt:
  db:
