services:

  orng-auth:
    image: bitmaximum/orng-auth:latest
    container_name: orng-auth
    restart: unless-stopped
    ports:
      - "${AUTH_PORT:-8080}:8080"
    environment:
      DB_URL: jdbc:postgresql://database:${PG_PORT:-5432}/${DB_NAME:-orng}?currentSchema=orng_auth
      DB_USER: orng
      DB_PASS: orng
      ACCESS_TOKEN_EXIRATION_SECONDS: 300
      REFRESH_TOKEN_EXIRATION_SECONDS: 604800
      JWT-ISSUER: orng-auth
      JWT-DEFAULT-USER-SCOPES: ROLE_MANAGER
      LOGGING_LEVEL_DEFAULT: TRACE
      JWT_PRIVATE_KEY: MIIEvAIBADANBgkqhkiG9w0BAQEFAASCBKYwggSiAgEAAoIBAQC98CHNAG1BkEsugNIvoWMCipKm8ifL7tcOg8kLMi4BBGFXCVUtgDtfCOjmjhdUml6KnNdw2SzdQxQvkXG86R8skeimZtQvXog7PyyGvbNJAYX7EleO5K9FgYZdXcl6m4T0i2o3Bk0gWkalrlbAX1E+3YFBCnjba3JAQ5mk0a3UeDiPVmdABz71S7vfQD1Q3Cv/LOvbta+X2evyzltRHZdqMe/HQXY+558PQLJekjL1F0kTa4eXg7t2Ibvfvzdie/qqHZe9L73yAN5JplpViPwyu7v4UV2CQOhZosdhJlrm4XDn9tSbOUJc7rLTj+qZpn5Fnwk4obiHb4cEAxkRQMzZAgMBAAECggEAIkGpFvw4uFZ5+M0rG4QUA2VSxeFu5A0TpH6ISAio224a0EPSpP43txA4UTzXYF7nJkDbanMA8HcksN+ej9/Ly5IVT83D/zchgu4F7ddQ+p3XuEy6lf8QzYxq23QK3p4mAKUUZxAv4OHnVAJ5iwCl+pygr0ZgPdLHLGgE0gEvRN6JuhhWszmdRWtLXy2Cx8QxutaYYY5QVhvXfpSOfYWIQeDfKGfZQtUrHYHPe0DKKUG77nl1IGxk3K/rC3N57z12wKZOMiG8iZQBSc3kodVZhinEsXz8rANXPvlPBN1HX/tcmioqfM+LZRdVQslRwpYWl6+YzBCiKvPLvAEbVCv08QKBgQD7fc3xo02oWPjqfjXAvkU57uCJqneUqqglRqzyacn0Kur/aGWlPo/dufTQQYG6XgQJ7Q6r2csnvN1k/7Nr6VE8y91sRHNQgJd6UBtz+OojehnRFbDFu0ajBGKNXUltD8tFBVyyTQQiwPAqEgLoQJluHUXhURhuhIrWgwZgA9NQ9wKBgQDBV9WLoFtSMQ9QVEltH9LGxKkvKY9/wgwkh6gv8NsXx/WRetzR5W8al/vQKFIbrOivKV1jBVVayFL8cbU39yTk5M/VAKoXFb4OK0mc0QMYO89Wf9RaPwzptkSD3abHQuKcvBPAmxfse3KoavLgplSu1J0Qx+JizBlN1VlvNq4srwKBgCdw1Wl9+OHcAj2USY3OyUCKrAArEdHo6bHe4aSq3pdCW9RuZPKDW0CktzYp79RwhiWgXdqpr2it//Kk/1h/INRuDG28VnFbmWX/Ri7r7Jxfu8jEpBJ+ildqiqIs7SUDgxdx/dWgqnNg2sleRcJyzx0rzhfGBhTfCH8X0Vohf3SFAoGAOawWofCybOD/fWm3AVsVx37QLKZMDML4Vkk07R/+aqiV4tBwYBf9PUSKs7vjSigYvG8tUSU9IbhRsMXGVaxeD/0E1be+BObSa22UJrfeIXNt1JKK6GSYWHqrE16hqhyUdkZP6gsZZswoFn7YdhSHfCMluuS07d2Nyr7ST69S4zcCgYAzff35tsUsO7MlMNSxPkz+gSLlDgWXcziOdOk9wqXmI0ZRQ+69mPqLmRnI2JEzbzR1PyovWKl0FTkJVo1sjgi2zbY2mKOtZ/9fZQBRPNN0LD8Z2MMaNNBsUzI2AhdhlEQfRTjjvEDZWj8aQhQO9OAmHhQQtQ5ltuWDoboM+/lThg==
      JWT_PUBLIC_KEY: MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAvfAhzQBtQZBLLoDSL6FjAoqSpvIny+7XDoPJCzIuAQRhVwlVLYA7Xwjo5o4XVJpeipzXcNks3UMUL5FxvOkfLJHopmbUL16IOz8shr2zSQGF+xJXjuSvRYGGXV3JepuE9ItqNwZNIFpGpa5WwF9RPt2BQQp422tyQEOZpNGt1Hg4j1ZnQAc+9Uu730A9UNwr/yzr27Wvl9nr8s5bUR2XajHvx0F2PuefD0CyXpIy9RdJE2uHl4O7diG73783Ynv6qh2XvS+98gDeSaZaVYj8Mru7+FFdgkDoWaLHYSZa5uFw5/bUmzlCXO6y04/qmaZ+RZ8JOKG4h2+HBAMZEUDM2QIDAQAB
      CORS_ALLOWED_ORIGINS: https://kiberorange.ru,http://kiberorange.ru,https://front.kiberorange.ru,http://www.kiberorange.ru,http://localhost:9006,http://127.0.0.1:9006
    depends_on:
      - database

  orng-office:
    image: bitmaximum/orng-office:latest
    container_name: orng-office
    restart: unless-stopped
    ports:
      - "${OFFICE_PORT:-8081}:8080"
    environment:
      DB_URL: jdbc:postgresql://database:${PG_PORT:-5432}/${DB_NAME:-orng}?currentSchema=orng_office
      DB_USER: ${DB_USER:-orng}
      DB_PASS: ${DB_PASS:-orng}
      JWT-ISSUER: orng-auth
      LOGGING_LEVEL_DEFAULT: TRACE
      CORS_ALLOWED_ORIGINS: https://kiberorange.ru,http://kiberorange.ru,https://front.kiberorange.ru,http://www.kiberorange.ru,http://localhost:9006,http://127.0.0.1:9006
      JWT_PUBLIC_KEY: MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAvfAhzQBtQZBLLoDSL6FjAoqSpvIny+7XDoPJCzIuAQRhVwlVLYA7Xwjo5o4XVJpeipzXcNks3UMUL5FxvOkfLJHopmbUL16IOz8shr2zSQGF+xJXjuSvRYGGXV3JepuE9ItqNwZNIFpGpa5WwF9RPt2BQQp422tyQEOZpNGt1Hg4j1ZnQAc+9Uu730A9UNwr/yzr27Wvl9nr8s5bUR2XajHvx0F2PuefD0CyXpIy9RdJE2uHl4O7diG73783Ynv6qh2XvS+98gDeSaZaVYj8Mru7+FFdgkDoWaLHYSZa5uFw5/bUmzlCXO6y04/qmaZ+RZ8JOKG4h2+HBAMZEUDM2QIDAQAB
    depends_on:
      - database

  employee-service:
    image: rumarsky/orng-employee:latest
    container_name: employee-service
    ports:
      - "${EM_PORT:-8082}:8080"
    environment:
      DB_URL: jdbc:postgresql://database:${PG_PORT:-5432}/${DB_NAME:-orng}?currentSchema=orng_employee
      DB_USER: ${DB_USER:-orng}
      DB_PASS: ${DB_PASS:-orng}
      OFFICE_SERVICE_URL: orng-office:8080
      JWT-ISSUER: orng-auth
      LOGGING_LEVEL_DEFAULT: TRACE
      CORS_ALLOWED_ORIGINS: https://kiberorange.ru,http://kiberorange.ru,https://front.kiberorange.ru,http://www.kiberorange.ru,http://localhost:9006,http://127.0.0.1:9006
      JWT_PUBLIC_KEY: MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAvfAhzQBtQZBLLoDSL6FjAoqSpvIny+7XDoPJCzIuAQRhVwlVLYA7Xwjo5o4XVJpeipzXcNks3UMUL5FxvOkfLJHopmbUL16IOz8shr2zSQGF+xJXjuSvRYGGXV3JepuE9ItqNwZNIFpGpa5WwF9RPt2BQQp422tyQEOZpNGt1Hg4j1ZnQAc+9Uu730A9UNwr/yzr27Wvl9nr8s5bUR2XajHvx0F2PuefD0CyXpIy9RdJE2uHl4O7diG73783Ynv6qh2XvS+98gDeSaZaVYj8Mru7+FFdgkDoWaLHYSZa5uFw5/bUmzlCXO6y04/qmaZ+RZ8JOKG4h2+HBAMZEUDM2QIDAQAB
    depends_on:
      - database
    restart: unless-stopped

  schedule-service:
    image: rumarsky/orng-schedule:latest
    container_name: schedule-service
    ports:
      - "${SS_PORT:-8083}:8080"
    environment:
      DB_URL: jdbc:postgresql://database:${PG_PORT:-5432}/${DB_NAME:-orng}?currentSchema=orng_schedule
      DB_USER: ${DB_USER:-orng}
      DB_PASS: ${DB_PASS:-orng}
      SERVER_PORT: 8080
      EMPLOYEE_SERVICE_URL: employee-service:8080
      OFFICE_SERVICE_URL: orng-office:8080
      JWT-ISSUER: orng-auth
      LOGGING_LEVEL_DEFAULT: TRACE
      CORS_ALLOWED_ORIGINS: https://kiberorange.ru,http://kiberorange.ru,https://front.kiberorange.ru,http://www.kiberorange.ru,http://localhost:9006,http://127.0.0.1:9006
      JWT_PUBLIC_KEY: MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAvfAhzQBtQZBLLoDSL6FjAoqSpvIny+7XDoPJCzIuAQRhVwlVLYA7Xwjo5o4XVJpeipzXcNks3UMUL5FxvOkfLJHopmbUL16IOz8shr2zSQGF+xJXjuSvRYGGXV3JepuE9ItqNwZNIFpGpa5WwF9RPt2BQQp422tyQEOZpNGt1Hg4j1ZnQAc+9Uu730A9UNwr/yzr27Wvl9nr8s5bUR2XajHvx0F2PuefD0CyXpIy9RdJE2uHl4O7diG73783Ynv6qh2XvS+98gDeSaZaVYj8Mru7+FFdgkDoWaLHYSZa5uFw5/bUmzlCXO6y04/qmaZ+RZ8JOKG4h2+HBAMZEUDM2QIDAQAB
    depends_on:
      - database
      - employee-service
    restart: unless-stopped

  database:
    image: 'postgres:18-alpine'
    container_name: 'postgres'
    restart: always
    environment:
      - POSTGRES_USER=orng
      - POSTGRES_PASSWORD=orng
      - POSTGRES_DB=orng
    volumes:
      - db:/var/lib/postgresql/data postgres
      - type: bind
        source: ./init.sql
        target: /docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432:5432"

volumes:
  npm_data:
  npm_letsencrypt:
  db:
